name: deployment
on:
  push:
    branches:
    - disabled
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Checkout this repository
      uses: actions/checkout@v2
    - name: Spawn a machine on Packet
      env:
        PACKET_TOKEN: ${{ secrets.PACKET_TOKEN }}
        PACKET_PROJECT_ID: ${{ secrets.PACKET_PROJECT_ID }}
      run: ./packet-device-create.sh
